import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import PrimaryButton from "@components/PrimaryButton";
import SecondaryButton from "@components/SecondaryButton";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
const UIKitWrapper = styled.div`
  display: flex;
  width: 100%;
  background-color: gray;
  justify-content: flex-start;
  align-items: center;
  flex-direction: row;
  flex-wrap: wrap;
  padding: 10px;
`;
const UiKitColumn = styled.div`
  width: auto;
  box-sizing: border-box;
  margin-left: 5px;
`;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UIKitWrapper>
        <UiKitColumn>
          <PrimaryButton title="Default" loading={false} disabled={false} />
        </UiKitColumn>
        <UiKitColumn>
          <SecondaryButton title="Default" loading={false} disabled={false} />
        </UiKitColumn>
      </UIKitWrapper>
    </div>
  );
};

export default Home;
